ALTER TABLE practitioner_request MODIFY COLUMN priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL';
ALTER TABLE practitioner_request MODIFY COLUMN status VARCHAR(20) NOT NULL DEFAULT 'PENDING';
ALTER TABLE practitioner_availability MODIFY COLUMN day_of_week VARCHAR(20) NOT NULL;
ALTER TABLE therapy_session MODIFY COLUMN status VARCHAR(20) NOT NULL DEFAULT 'BOOKED';
ALTER TABLE therapy_session MODIFY COLUMN session_type VARCHAR(20) NOT NULL DEFAULT 'ONLINE';
ALTER TABLE therapy_session MODIFY COLUMN payment_status VARCHAR(20) NOT NULL DEFAULT 'PENDING';
ALTER TABLE therapy_session MODIFY COLUMN cancelled_by VARCHAR(20);



